name: Solidity

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment for workflow execution"
        required: false
        default: "dev"
      upstream_builds:
        description: "Upstream builds"
        required: false
      upstream_ref:
        description: "Git reference to checkout (e.g. branch name)"
        required: false
        default: "main"

jobs:
  contracts-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build contracts
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Run system tests
        env:
          FORKING_URL: ${{ secrets.MAINNET_ETH_HOSTNAME }}
        run: yarn test:system

  contracts-deployment-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Deploy contracts
        run: yarn deploy

  contracts-deployment-testnet:
    needs: [contracts-build-and-test]
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Load environment variables
        uses: keep-network/ci/actions/load-env-variables@move-actions-to-ci # TODO: change to @v1 before merging to main
        with:
          environment: ${{ github.event.inputs.environment }}

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Get upstream packages' versions
        uses: keep-network/ci/actions/upstream-builds-query@move-actions-to-ci # TODO: change to @v1 before merging to main
        id: upstream-builds-query
        with:
          upstream-builds: ${{ github.event.inputs.upstream_builds }}
          query: |
            keep-core-solidity-version = github.com/keep-network/keep-core/solidity#version
            tbtc-solidity-version = github.com/keep-network/tbtc/solidity#version

      - name: Resolve latest contracts
        if: github.event_name == 'workflow_dispatch'
        run: |
          yarn add \
            @keep-network/keep-core@${{ steps.upstream-builds-query.outputs.keep-core-solidity-version }} \
            @keep-network/tbtc@${{ steps.upstream-builds-query.outputs.tbtc-solidity-version }}

      - name: Deploy contracts
        run: yarn deploy --network ${{ github.event.inputs.environment }}

      - name: Bump up package version
        id: npm-version-bump
        uses: keep-network/npm-version-bump@v2
        with:
          environment: ${{ github.event.inputs.environment }}
          branch: ${{ github.ref }}
          commit: ${{ github.sha }}

      - name: Push contracts to Tenderly
        if: github.event.inputs.environment == 'ropsten'
        # TODO: once below action gets tagged replace `@main` with `@v1`
        uses: keep-network/tenderly-push-action@main
        continue-on-error: true
        with:
          tenderly-token: ${{ secrets.TENDERLY_TOKEN }}
          tenderly-project: thesis/keep-test
          eth-network-id: ${{ env.NETWORK_ID }}
          github-project-name: coverage-pools
          version-tag: ${{ steps.npm-version-bump.outputs.version }}

      - name: Publish to npm
        run: | #TODO: remove `--dry-run` before merging
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
          npm publish --access=public --dry-run

      - name: Notify CI about completion of the workflow
        uses: keep-network/ci/actions/notify-workflow-completed@move-actions-to-ci # TODO: change to @v1 before merging to main
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        with:
          module: "github.com/keep-network/coverage-pools"
          url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          environment: ${{ github.event.inputs.environment }}
          upstream_builds: ${{ github.event.inputs.upstream_builds }}
          upstream_ref: ${{ github.event.inputs.upstream_ref }}
          version: ${{ steps.npm-version-bump.outputs.version }}

  contracts-lint:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

  contracts-slither:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: "yarn"

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.5

      - name: Install Solidity
        env:
          SOLC_VERSION: 0.8.4 # according to solidity.version in hardhat.config.ts
        run: |
          pip3 install solc-select
          solc-select install $SOLC_VERSION
          solc-select use $SOLC_VERSION

      - name: Install Slither
        env:
          SLITHER_VERSION: 0.8.0
        run: pip3 install slither-analyzer==$SLITHER_VERSION

      - name: Install dependencies
        run: yarn install

      - name: Run Slither
        run: slither .
