name: Solidity

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment for workflow execution"
        required: false
        default: "dev"
      upstream_builds:
        description: "Upstream builds"
        required: false
      upstream_ref:
        description: "Git reference to checkout (e.g. branch name)"
        required: false
        default: "main"

jobs:
  contracts-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"

      # We need this step because the `@keep-network/tbtc` which we install in
      # next step has a dependency to `@summa-tx/relay-sol@2.0.2` package, which
      # downloads one of its sub-dependencies via unathenticated `git://`
      # protocol. That protocol is no longer supported. Thanks to this step
      # `https://` is used instead of `git://`.
      - name: Configure git to don't use unauthenticated protocol
        shell: bash
        run: git config --global url."https://".insteadOf git://

      - name: Install dependencies
        run: yarn install

      - name: Build contracts
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Run system tests
        env:
          FORKING_URL: ${{ secrets.MAINNET_ETH_HOSTNAME }}
        run: yarn test:system

  contracts-deployment-dry-run:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"

      # We need this step because the `@keep-network/tbtc` which we install in
      # next step has a dependency to `@summa-tx/relay-sol@2.0.2` package, which
      # downloads one of its sub-dependencies via unathenticated `git://`
      # protocol. That protocol is no longer supported. Thanks to this step
      # `https://` is used instead of `git://`.
      - name: Configure git to don't use unauthenticated protocol
        shell: bash
        run: git config --global url."https://".insteadOf git://

      - name: Install dependencies
        run: yarn install

      - name: Deploy contracts
        run: yarn deploy

  contracts-deployment-testnet:
    needs: [contracts-build-and-test]
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      # We need this step because the `@keep-network/tbtc` which we install in
      # next step has a dependency to `@summa-tx/relay-sol@2.0.2` package, which
      # downloads one of its sub-dependencies via unathenticated `git://`
      # protocol. That protocol is no longer supported. Thanks to this step
      # `https://` is used instead of `git://`.
      - name: Configure git to don't use unauthenticated protocol
        shell: bash
        run: git config --global url."https://".insteadOf git://

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Resolve latest contracts
        run: |
          yarn upgrade \
            @keep-network/keep-core@${{ github.event.inputs.environment }} \
            @keep-network/tbtc@${{ github.event.inputs.environment }} \
            @threshold-network/solidity-contracts@${{ github.event.inputs.environment }}

      - name: Configure tenderly
        env:
          TENDERLY_TOKEN: ${{ secrets.TENDERLY_TOKEN }}
        run: ./config_tenderly.sh

      - name: Deploy contracts
        env:
          CHAIN_API_URL: ${{ secrets.GOERLI_ETH_HOSTNAME_HTTP }}
          ACCOUNTS_PRIVATE_KEYS: ${{ secrets.GOERLI_ETH_CONTRACT_OWNER_PRIVATE_KEY }}
        run: yarn deploy --network ${{ github.event.inputs.environment }}

      - name: Bump up package version
        id: npm-version-bump
        uses: keep-network/npm-version-bump@v2
        with:
          environment: ${{ github.event.inputs.environment }}
          branch: ${{ github.ref }}
          commit: ${{ github.sha }}

      - name: Publish to npm
        # TODO: remove `--dry-run` before merge to main
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access=public --network=${{ github.event.inputs.environment }} --tag ${{ github.event.inputs.environment }}  --dry-run

      # We're systematically moving to the v2 of the system, where different
      # order of execution of modules is needed than in v1. `coverage-pools` are
      # not yet ready to be included in the new (v2) CI flow. And the old (v1)
      # deployment flow is now deprecated. Once coverage-pools get adjusted for
      # the use in T dashboard, we'll need to uncomment this step and modify it
      # for v2.
      # - name: Notify CI about completion of the workflow
      #   uses: keep-network/ci/actions/notify-workflow-completed@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
      #   with:
      #     module: "github.com/keep-network/coverage-pools"
      #     url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      #     environment: ${{ github.event.inputs.environment }}
      #     upstream_builds: ${{ github.event.inputs.upstream_builds }}
      #     upstream_ref: ${{ github.event.inputs.upstream_ref }}
      #     version: ${{ steps.npm-version-bump.outputs.version }}

      - name: Upload files needed for etherscan verification
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts for etherscan verifcation
          path: |
            ./deployments
            ./package.json
            ./yarn.lock

  contracts-etherscan-verification:
    needs: [contracts-deployment-testnet]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download files needed for etherscan verification
        uses: actions/download-artifact@v2
        with:
          name: Artifacts for etherscan verifcation

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"

      # We need this step because the `@keep-network/tbtc` which we install in
      # next step has a dependency to `@summa-tx/relay-sol@2.0.2` package, which
      # downloads one of its sub-dependencies via unathenticated `git://`
      # protocol. That protocol is no longer supported. Thanks to this step
      # `https://` is used instead of `git://`.
      - name: Configure git to don't use unauthenticated protocol
        shell: bash
        run: git config --global url."https://".insteadOf git://

      - name: Install needed dependencies
        run: yarn install --frozen-lockfile

      # If we don't remove the dependencies' contracts from `node-modules`, the
      # `etherscan-verify` plugins tries to verify them, which is not desired.
      - name: Prepare for verification on Etherscan
        run: |
          rm -rf ./node_modules/@keep-network/keep-core
          rm -rf ./node_modules/@keep-network/tbtc
          rm -rf ./node_modules/@threshold-network/solidity-contracts

      - name: Verify contracts on Etherscan
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          CHAIN_API_URL: ${{ secrets.GOERLI_ETH_HOSTNAME_HTTP }}
        run: yarn run hardhat --network ${{ github.event.inputs.environment }} etherscan-verify --license MIT

  contracts-lint:
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'workflow_dispatch'
        && github.event_name != 'schedule'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"

      # We need this step because the `@keep-network/tbtc` which we install in
      # next step has a dependency to `@summa-tx/relay-sol@2.0.2` package, which
      # downloads one of its sub-dependencies via unathenticated `git://`
      # protocol. That protocol is no longer supported. Thanks to this step
      # `https://` is used instead of `git://`.
      - name: Configure git to don't use unauthenticated protocol
        shell: bash
        run: git config --global url."https://".insteadOf git://

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

  contracts-slither:
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'workflow_dispatch'
        && github.event_name != 'schedule'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.5

      - name: Install Solidity
        env:
          SOLC_VERSION: 0.8.5 # according to solidity.version in hardhat.config.js
        run: |
          pip3 install solc-select
          solc-select install $SOLC_VERSION
          solc-select use $SOLC_VERSION

      - name: Install Slither
        env:
          SLITHER_VERSION: 0.8.3
        run: pip3 install slither-analyzer==$SLITHER_VERSION

      # We need this step because the `@keep-network/tbtc` which we install in
      # next step has a dependency to `@summa-tx/relay-sol@2.0.2` package, which
      # downloads one of its sub-dependencies via unathenticated `git://`
      # protocol. That protocol is no longer supported. Thanks to this step
      # `https://` is used instead of `git://`.
      - name: Configure git to don't use unauthenticated protocol
        shell: bash
        run: git config --global url."https://".insteadOf git://

      - name: Install dependencies
        run: yarn install

      - name: Run Slither
        run: slither .
