name: Code Format Checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  code-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      # This step forces Git to download dependencies using `https://` protocol,
      # even if `yarn.json` refers to some package via `git://`. Using `git://`
      # is no longer supported by GH. One of the `coverage-pools` dependencies
      # by default uses `git://` and we needed to manually remove it every time
      # it re-appeares in the lock file. Now even if it does re-appear, the
      # `yarn install --frozen-lockfile` will not fail.

      - name: Install dependencies
        run: yarn install

      - name: Check formatting
        run: yarn format
