name: NPM

on:
  push:
    branches:
      - main
    paths:
      - "contracts/**"
      - "deploy/**"
      - "hardhat.config.ts"
      - "package.json"
      - "yarn.lock"
  workflow_dispatch:

jobs:
  npm-compile-publish-contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"

      # We need this step because the `@keep-network/tbtc` which we update in
      # next step has a dependency to `@summa-tx/relay-sol@2.0.2` package, which
      # downloads one of its sub-dependencies via unathenticated `git://`
      # protocol. That protocol is no longer supported. Thanks to this step
      # `https://` is used instead of `git://`.
      - name: Configure git to don't use unauthenticated protocol
        shell: bash
        run: git config --global url."https://".insteadOf git://

      - name: Resolve latest contracts
        run: |
          yarn upgrade \
            @keep-network/keep-core \
            @keep-network/tbtc \
            @threshold-network/solidity-contracts

      # Deploy contracts to a local network to generate deployment artifacts that
      # are required by dashboard compilation.
      - name: Deploy contracts
        run: yarn deploy --network hardhat --write true

      - name: Bump up package version
        id: npm-version-bump
        uses: keep-network/npm-version-bump@v2
        with:
          environment: dev
          branch: ${{ github.ref }}
          commit: ${{ github.sha }}

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access=public --network=hardhat --tag=development
